[formant]
agent-server-port-grpc = "5501"
agent-server-port-http = "5502"
agent-server-ip = "localhost"

#### Example robot tags ####

[tags]
name = "turtle-0002"
group = "floor-3"
location = "SF-001"
customer = "Bay Area Widget Co."


#### ROS Global configuration ####

[ros]
# the name of a common reference frame relative to which any ROS messages associated with a `frame_id` will be expressed
world-reference-frame-id = "world_frame"


##### ROS Streams #####

[[streams]]
name = "battery.voltage"
ros-topic = "/battery/voltage"

[[streams]]
name = "arm.position"
ros-topic = "/joint_states/joint_1"
ros-path = "data" ## this will pull the internal 'data' object from the message on this topic.

[[streams]]
name = "localization"
ros-odom-topic = "/odom" # A ROS nav_msgs/Odometry message
ros-map-topic = "/map" # A ROS nav_msgs/OccupancyGrid message
